import {test,expect} from '@playwright/test';
import {waitForHomepage} from './helpers/homepage-ready';
const origin=process.env.LGO_WEB_URL??'http://127.0.0.1:3221';
test.describe('homepage lower media and footer v1.265 revision4',()=>{
 test.beforeEach(async({page})=>{await page.goto(origin+'/');await waitForHomepage(page);});
 test('discovery uses dedicated dark world artwork rather than the bright old skyline or a baked UI board',async({page})=>{const lead=page.locator('#home-discovery .lgo-media-mosaic-lead img');await expect(lead).toHaveAttribute('src','/game-art/marketing/discovery-world.png');const info=await lead.evaluate(i=>({w:i.naturalWidth,h:i.naturalHeight,loaded:i.complete&&i.naturalWidth>0}));expect(info.loaded).toBe(true);expect(info.w).toBeGreaterThanOrEqual(480);expect(info.h).toBeGreaterThanOrEqual(220);await expect(page.locator('main img[src*=design-reference],main video,main iframe')).toHaveCount(0);});
 test('discovery lead has a decorative portal focal mark, never a fake video control',async({page})=>{
  const wrap=page.locator('#home-discovery .lgo-media-mosaic-lead-wrap'),lead=wrap.locator('.lgo-media-mosaic-lead');await expect(wrap.locator('.lgo-media-mosaic-focal')).toHaveCount(1);await expect(wrap.locator('.lgo-media-mosaic-focal')).toHaveAttribute('aria-hidden','true');await expect(wrap.locator('video,iframe,button,[role=button]')).toHaveCount(0);await expect(lead).toHaveAttribute('href','/game');
 });
 test('news cards use three distinct editorial thumbnails and do not repeat the feature-card images',async({page})=>{const news=await page.locator('#home-news .lgo-editorial-preview-card > img').evaluateAll(nodes=>nodes.map(i=>i.getAttribute('src')));expect(news).toEqual(['/game-art/marketing/news-event.png','/game-art/marketing/news-update.png','/game-art/marketing/news-community.png']);expect(new Set(news).size).toBe(3);const features=await page.locator('.lgo-landing-features > a > img').evaluateAll(nodes=>nodes.map(i=>i.getAttribute('src')));expect(news.some(x=>features.includes(x))).toBe(false);});
 test('desktop discovery and news retain paired visual weight with source-backed article controls',async({page,isMobile})=>{const d=await page.locator('#home-discovery').boundingBox(),n=await page.locator('#home-news').boundingBox();if(!isMobile){expect(Math.abs(d!.y-n!.y)).toBeLessThan(2);expect(Math.abs(d!.height-n!.height)).toBeLessThan(90);}const cards=page.locator('#home-news .lgo-editorial-preview-card');await expect(cards).toHaveCount(3);for(const card of await cards.all()){await expect(card.getByRole('link')).toHaveCount(1);await expect(card.locator('details')).toHaveCount(1);}});
 test('immersive footer mirrors the compact design rhythm but keeps truthful public availability',async({page,isMobile})=>{const footer=page.locator('.lgo-marketing-footer');await expect(footer).toBeVisible();await expect(footer.locator('.lgo-art-wordmark')).toBeVisible();await expect(footer).toContainText('Sống một đời khác trong Linh Giới');await expect(footer).toContainText('Bản public chưa mở');await expect(footer.getByRole('link',{name:'Xem trạng thái chơi'})).toHaveAttribute('href','/download');await expect(footer).not.toContainText('Máy chủ hoạt động ổn định');await expect(footer).not.toContainText('Windows');const grid=await footer.evaluate(e=>getComputedStyle(e.querySelector('.lgo-marketing-footer-inner')!).gridTemplateColumns.split(' ').length);expect(grid).toBe(isMobile?1:3);});
 test('footer and lower media keep44px keyboard targets, forced-color focus and no horizontal overflow',async({page})=>{await page.setViewportSize({width:320,height:900});for(const e of await page.locator('#home-discovery a,#home-news a,#home-news summary,.lgo-marketing-footer a').all()){if(await e.isVisible())expect((await e.boundingBox())!.height).toBeGreaterThanOrEqual(44);}const link=page.locator('.lgo-marketing-footer a').first();await link.focus();await page.emulateMedia({forcedColors:'active'});expect(await link.evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(0);});
 test('lower-art failure leaves real text navigation and truthful footer usable',async({page})=>{await page.route('**/game-art/marketing/{discovery-world,news-*}.png',r=>r.abort());await page.reload();await waitForHomepage(page);await expect(page.locator('#home-discovery h2')).toBeVisible();await expect(page.locator('#home-news h2')).toBeVisible();await expect(page.locator('.lgo-marketing-footer')).toContainText('Bản public chưa mở');await page.locator('#home-news h3 a').first().click();await expect(page).toHaveURL(/\/news\//);});
});
