import {test,expect} from '@playwright/test';
import {narrativeChapters} from '../../packages/content/src/fixtures';
const origin=process.env.LGO_WEB_URL??'http://127.0.0.1:3236';
test.describe('story visual realignment v1.267',()=>{
 test.beforeEach(async({page})=>{await page.goto(origin+'/story',{waitUntil:'networkidle'});});
 test('replaces generic proof cards with an immersive story target hierarchy',async({page,isMobile})=>{
  await expect(page.locator('.lgo-public-shell-immersive')).toHaveCount(1);const hero=page.locator('.lgo-story-landing-hero');await expect(hero).toBeVisible();await expect(hero.getByRole('heading',{level:1})).toHaveText('Cho đến ngày những cánh cửa bắt đầu mở');
  await expect(page.locator('.lgo-storypage-expanded-evidence,.lgo-cinematic-hero')).toHaveCount(0);const box=await hero.boundingBox();expect(box!.height).toBeGreaterThan(isMobile?540:360);expect(box!.height).toBeLessThan(isMobile?800:600);
 });
 test('desktop hero keeps the target title measure and foreground character layer',async({page,isMobile})=>{if(isMobile)return;const title=await page.locator('.lgo-story-landing-copy h1').boundingBox();expect(title!.height).toBeLessThan(225);const layers=await page.evaluate(()=>({character:Number.parseInt(getComputedStyle(document.querySelector('.lgo-story-hero-character')!).zIndex,10),gate:Number.parseInt(getComputedStyle(document.querySelector('.lgo-story-hero-gate')!).zIndex,10)}));expect(layers.character).toBeGreaterThan(layers.gate);});
 test('uses separate source-derived artwork and never embeds the design board or a fake trailer',async({page,isMobile})=>{
  const heroImages=page.locator('.lgo-story-landing-art img');await expect(heroImages).toHaveCount(isMobile?1:2);for(const img of await heroImages.all()){const d=await img.evaluate(i=>({nw:i.naturalWidth,nh:i.naturalHeight,complete:i.complete,src:i.currentSrc}));expect(d.complete).toBe(true);expect(d.nw).toBeGreaterThan(280);expect(d.nh).toBeGreaterThan(300);expect(d.src).not.toContain('design-reference');}
  await expect(page.locator('main img[src*=design-reference],main video,main iframe,main canvas,main a[download]')).toHaveCount(0);await expect(page.locator('main')).not.toContainText(/xem trailer|trailer cốt truyện/i);
 });
 test('renders three source chapters plus one clearly narrative event card',async({page})=>{
  const cards=page.locator('.lgo-story-chapter-card');await expect(cards).toHaveCount(4);for(const [i,chapter]of narrativeChapters.entries()){const card=cards.nth(i);await expect(card.getByRole('heading',{level:3})).toHaveText(chapter.title);await expect(card).toHaveAttribute('aria-label',new RegExp(chapter.hook.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));}
  const event=cards.nth(3);await expect(event).toContainText('BIẾN CỐ CỐT TRUYỆN');await expect(event.getByRole('heading',{level:3})).toHaveText('Âm Giới Xâm Lăng');await expect(event).not.toContainText(/đang diễn ra|tham gia ngay/i);
 });
 test('story cards follow target four-column rhythm on desktop and stack on mobile',async({page,isMobile})=>{const cols=await page.locator('.lgo-story-chapter-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length);expect(cols).toBe(isMobile?1:4);});
 test('desktop story chapter grid occupies the target reading width',async({page,isMobile})=>{if(isMobile)return;const grid=await page.locator('.lgo-story-chapter-grid').boundingBox();const card=await page.locator('.lgo-story-chapter-card').first().boundingBox();expect(grid!.width).toBeGreaterThan(1200);expect(card!.width).toBeGreaterThan(250);});
 test('desktop hero title follows the target three-line rhythm',async({page,isMobile})=>{if(isMobile)return;const lines=await page.locator('.lgo-story-landing-copy h1').evaluate(e=>{const range=document.createRange();range.selectNodeContents(e);return range.getClientRects().length;});expect(lines).toBe(3);});
 test('story actions are truthful reading routes and keyboard reachable',async({page})=>{const actions=page.locator('.lgo-story-landing-actions a');await expect(actions).toHaveCount(2);await expect(actions.nth(0)).toHaveAttribute('href','#chapters');await expect(actions.nth(1)).toHaveAttribute('href','/journey');await actions.nth(0).focus();await page.keyboard.press('Enter');await expect(page.locator('#chapters')).toBeFocused();await actions.nth(1).click();await expect(page).toHaveURL(origin+'/journey');});
 test('desktop story density remains near the target instead of long proof-board evidence',async({page,isMobile})=>{if(isMobile)return;expect(await page.evaluate(()=>document.documentElement.scrollHeight)).toBeLessThan(1250);expect((await page.locator('.lgo-story-chapter-grid').boundingBox())!.height).toBeLessThan(300);});
 test('320px copy controls and focus remain readable',async({page})=>{await page.setViewportSize({width:320,height:800});expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(0);for(const p of await page.locator('.lgo-story-landing p').all()){if(await p.isVisible())expect(await p.evaluate(e=>parseFloat(getComputedStyle(e).fontSize))).toBeGreaterThanOrEqual(14);}for(const a of await page.locator('.lgo-story-landing a').all()){if(await a.isVisible())expect((await a.boundingBox())!.height).toBeGreaterThanOrEqual(44);}const a=page.locator('.lgo-story-landing-actions a').first();await a.focus();expect(await a.evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');});
});
