export {
  NOT_CANONICAL_BACKEND_CONTRACT,
  PROVISIONAL_WEB_FIXTURE,
  beginnerGuideSections,
  communityPrinciples,
  communityReadinessSteps,
  communityOnboardingPaths,
  communityFeedbackChannels,
  roadmapDecisionGates,
  stagedReleaseMessages,
  publicRouteGroups,
  playerEntryQuestions,
  publicContentHubs,
  gameplayLoopStages,
  beginnerExpectations,
  guideWorldNavigationLinks,
  gameplayScopeBoundaries,
  playerSafetyPrinciples,
  supportIssuePaths,
  closedTestSupportExpectations,
  communityConductRules,
  accessibilityReadabilityPrinciples,
  routeReadabilityChecks,
  mobileScannabilityRules,
  focusOrderCheckpoints,
  performanceCopyBudgetPrinciples,
  staticRouteCompositionRules,
  perceivedLoadSignals,
  mobileDensityBudgets,
  routeContinuityBridges,
  conversionSafeCtas,
  journeyFrictionChecks,
  pageCohesionCheckpoints,
  playerTrustSignals,
  releaseNarrativeStages,
  closedTestReadinessChecks,
  trustJourneyCheckpoints,
  releaseReadinessHubItems,
  ownerReleaseGates,
  testerExpectationCopy,
  releaseSurfaceAlignment,
  closedTesterChecklist,
  safeFeedbackTemplates,
  knownLimitationNotes,
  deviceReportTemplateFields,
  faqDiscoveryGroups,
  faqHelpfulnessPrompts,
  issueCategoryRoutes,
  noSearchBackendNotes,
  contentDetailSections,
  guideDetailSteps,
  downloadExplainers,
  statusExplainers,
  contentEntries,
  downloadBuilds,
  downloadReadiness,
  downloadStatusNotes,
  downloadTrustGates,
  releaseEvidenceRequirements,
  statusTrustSurfaces,
  playerSupportExpectations,
  playerJourneySteps,
  publicHeroStats,
  publicPageFocus,
  publicRoadmapItems,
  responsiveBreakpoints,
  supportFaqs,
  supportTopics,
  visualPolishItems,
  worldPillars,
  worldStoryChapters,
  gameExperiencePillars,
  classPaths,
  worldRouteStops,
  narrativeChapters,
  sampleSessionBeats,
  publicGameArtAssets,
  homeDiscoveryMoments
} from "./fixtures";
export { LocalContentRepository, localContentRepository } from "./repository";
export {
  archiveNewsEntries,
  currentNewsPolicy,
  playerNewsEntries,
  publicLanguageContract,
  publicRouteMatrix,
  routePolicy
} from "./public-ia";
export {
  PUBLIC_SITE_ORIGIN,
  publicLastModifiedForRoute,
  publicMetadataForRoute
} from "./public-metadata";
export type { PublicMetadataSource } from "./public-metadata";
export type {
  PublicDiscovery,
  PublicIndexability,
  PublicLanguageProfile,
  PublicRouteOwner,
  PublicRoutePolicy
} from "./public-ia";
export { assertContentFixturesValid, findDuplicateSlugs, findInvalidDates, findInvalidSlugs } from "./validation";
export type {
  CommunityPrinciple,
  CommunityReadinessStep,
  ContentDetailSection,
  GuideDetailStep,
  DownloadExplainer,
  StatusExplainer,
  SupportFaq,
  DownloadStatusNote,
  BeginnerGuideSection,
  ContentCategory,
  ContentEntry,
  ContentRepository,
  DownloadBuild,
  DownloadReadiness,
  PlayerJourneyStep,
  PublicHeroStat,
  PublicPageFocus,
  PublicRoadmapItem,
  PublishStatus,
  ResponsiveBreakpoint,
  SupportTopic,
  VisualPolishItem,
  DownloadTrustGate,
  ReleaseEvidenceRequirement,
  StatusTrustSurface,
  PlayerSupportExpectation,
  CommunityOnboardingPath,
  CommunityFeedbackChannel,
  RoadmapDecisionGate,
  StagedReleaseMessage,
  ContentHubRoute,
  PublicRouteGroup,
  PlayerEntryQuestion,
  PublicContentHub,
  GameplayLoopStage,
  BeginnerExpectation,
  GuideWorldNavigationLink,
  GameplayScopeBoundary,
  PlayerSafetyPrinciple,
  SupportIssuePath,
  ClosedTestSupportExpectation,
  CommunityConductRule,
  AccessibilityReadabilityPrinciple,
  RouteReadabilityCheck,
  MobileScannabilityRule,
  FocusOrderCheckpoint,
  PerformanceCopyBudgetPrinciple,
  StaticRouteCompositionRule,
  PerceivedLoadSignal,
  MobileDensityBudget,
  RouteContinuityBridge,
  ConversionSafeCta,
  JourneyFrictionCheck,
  PageCohesionCheckpoint,
  PlayerTrustSignal,
  ReleaseNarrativeStage,
  ClosedTestReadinessCheck,
  TrustJourneyCheckpoint,
  ReleaseReadinessHubItem,
  OwnerReleaseGate,
  TesterExpectationCopy,
  ReleaseSurfaceAlignment,
  ClosedTesterChecklistItem,
  SafeFeedbackTemplate,
  KnownLimitationNote,
  DeviceReportTemplateField,
  FaqDiscoveryGroup,
  FaqHelpfulnessPrompt,
  IssueCategoryRoute,
  NoSearchBackendNote,
  WorldStoryChapter,
  WorldPillar,
  GameExperiencePillar,
  ClassPath,
  WorldRouteStop,
  NarrativeChapter,
  SessionBeat,
  PublicGameArtAsset,
  HomeDiscoveryMoment
} from "./types";

export const contentStatus = {
  model: "file-backed typed local content",
  cms: "NO_CMS",
  backend: "NO_BACKEND_INTEGRATION",
  note: "file-backed content is source-owned until WEB-08+ explicit contract sync"
} as const;
