import { closedTesterChecklist, deviceReportTemplateFields, knownLimitationNotes, safeFeedbackTemplates } from "@lgo-web/content";
import { GameCard, Grid, LinkButton, SectionHeading, StatusBadge } from "@lgo-web/ui";

export function ClosedTesterChecklistBoard() {
  return <section className="lgo-panel lgo-service-proof-card-grid lgo-closed-tester-checklist-board" aria-labelledby="closed-tester-checklist-heading"><SectionHeading headingId="closed-tester-checklist-heading" eyebrow="Gói tester cộng đồng" title="Checklist chuẩn bị, không mở đăng ký giả">Checklist này giúp người chơi biết nên đọc gì, chuẩn bị gì và chưa nên kỳ vọng gì trước khi có kênh closed-test chính thức.</SectionHeading><Grid id="closed-tester-checklist-heading-items">{closedTesterChecklist.map((item) => <GameCard className="lgo-service-proof-card lgo-closed-tester-card" key={item.id}><StatusBadge tone="gold">{item.title}</StatusBadge><h3>{item.testerQuestion}</h3><p>{item.safePreparation}</p><small>{item.nonClaim}</small><LinkButton href={item.whereToRead} tone="spirit">Đọc trang liên quan</LinkButton></GameCard>)}</Grid></section>;
}

export function SafeFeedbackTemplateBoard() {
  return <section className="lgo-panel lgo-service-proof-card-grid lgo-safe-feedback-template-board" aria-labelledby="safe-feedback-template-heading"><SectionHeading headingId="safe-feedback-template-heading" eyebrow="Feedback an toàn" title="Mẫu feedback rõ ràng, không thu dữ liệu nhạy cảm">Mẫu feedback ưu tiên tóm tắt, bước tái hiện và kỳ vọng/thực tế; mỗi trường đều có privacy boundary.</SectionHeading><div id="safe-feedback-template-heading-items" className="lgo-service-proof-list lgo-safe-feedback-list">{safeFeedbackTemplates.map((item) => <article className="lgo-service-proof-item lgo-safe-feedback-item" key={item.field}><StatusBadge tone="jade">{item.field}</StatusBadge><h3>{item.guidance}</h3><p><strong>Ví dụ:</strong> {item.example}</p><small>{item.privacyBoundary}</small></article>)}</div></section>;
}

export function KnownLimitationNotesBoard() {
  return <section className="lgo-panel lgo-service-proof-card-grid lgo-known-limitation-board" aria-labelledby="known-limitation-heading"><SectionHeading headingId="known-limitation-heading" eyebrow="Giới hạn đã biết" title="Nói rõ giới hạn trước khi bị hiểu nhầm là bản test mở">Giới hạn đã biết giúp tester tương lai hiểu điều gì chưa có, bằng chứng nào còn thiếu và claim nào bị cấm.</SectionHeading><Grid id="known-limitation-heading-items">{knownLimitationNotes.map((item) => <GameCard className="lgo-service-proof-card lgo-known-limitation-card" key={item.area}><StatusBadge tone="shadow">{item.area}</StatusBadge><h3>{item.playerMessage}</h3><p>{item.ownerNote}</p><small>{item.mustNotClaim}</small></GameCard>)}</Grid></section>;
}

export function DeviceReportTemplateBoard() {
  return <section className="lgo-panel lgo-service-proof-card-grid lgo-device-report-template-board" aria-labelledby="device-report-template-heading"><SectionHeading headingId="device-report-template-heading" eyebrow="Mẫu báo cáo thiết bị" title="Chỉ ghi đủ để tái hiện lỗi, không thu định danh">Template này mô tả field an toàn cho feedback sau này: loại thiết bị, OS/browser/screen, bối cảnh mạng và ảnh/log đã che dữ liệu.</SectionHeading><div id="device-report-template-heading-items" className="lgo-service-proof-list lgo-device-report-list">{deviceReportTemplateFields.map((item) => <article className="lgo-service-proof-item lgo-device-report-item" key={item.field}><StatusBadge tone="spirit">{item.field}</StatusBadge><h3>{item.whyItMatters}</h3><p><strong>Định dạng an toàn:</strong> {item.safeFormat}</p><small>{item.doNotCollect}</small></article>)}</div></section>;
}

export function ClosedTesterInformationPackCta() {
  return <section className="lgo-detail-next-steps lgo-closed-tester-info-cta" aria-label="Bước tiếp theo cho gói tester"><div><StatusBadge tone="gold">WEB v1.144 gói tester cộng đồng</StatusBadge><h2>Chuẩn bị hướng dẫn tester trước, không mở nhận đăng ký hoặc hứa suất test.</h2><p>Đọc checklist, feedback an toàn, giới hạn đã biết và mẫu báo cáo thiết bị để hiểu mức sẵn sàng closed test mà không gửi bí mật hoặc dữ liệu nhạy cảm.</p></div><div className="lgo-product-first-actions"><LinkButton href="/release/tester-pack" tone="gold">Gói tester</LinkButton><LinkButton href="/release/readiness" tone="spirit">Sẵn sàng phát hành</LinkButton><LinkButton href="/support/safety" tone="jade">Hỗ trợ an toàn</LinkButton></div></section>;
}
