import {test,expect} from 'vitest';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {EditorialPreviewCard, MarketingFooter} from '../../packages/ui/src/home-editorial';
const image={src:'/thumb.png',width:242,height:91};
test('editorial preview keeps one real title link and one full native summary disclosure',()=>{const html=renderToStaticMarkup(createElement(EditorialPreviewCard,{title:'Tin nguồn',href:'/news/source',dateTime:'2026-09-05T00:00:00.000Z',dateLabel:'05/09/2026',category:'Nhật ký web',summary:'Tóm tắt đầy đủ',image}));expect((html.match(/<a /g)||[])).toHaveLength(1);expect(html).toContain('href="/news/source"');expect(html).toContain('<details>');expect(html).toContain('Tóm tắt đầy đủ');});
test('editorial preview escapes all source text and uses decorative imagery',()=>{const html=renderToStaticMarkup(createElement(EditorialPreviewCard,{title:'<script>x</script>',href:'/news/source',dateTime:'2026-09-05T00:00:00.000Z',dateLabel:'05/09/2026',category:'Nguồn',summary:'<img>',image}));expect(html).toContain('&lt;script&gt;');expect(html).toContain('&lt;img&gt;');expect(html).toContain('alt=""');});
test('immersive footer keeps brush brand, truthful state and only caller-supplied links',()=>{const html=renderToStaticMarkup(createElement(MarketingFooter,{brandSrc:'/wordmark.png',brandWidth:422,brandHeight:169,brandLabel:'Linh Giới Online',tagline:'Sống một đời khác trong Linh Giới',status:'Bản public chưa mở',statusHref:'/download',links:[{href:'/status',label:'Trạng thái'},{href:'/support',label:'Hỗ trợ'}]}));expect(html).toContain('lgo-marketing-footer');expect(html).toContain('Bản public chưa mở');expect(html).toContain('href="/download"');expect(html).toContain('href="/status"');expect(html).not.toContain('Windows');expect(html).not.toContain('Máy chủ hoạt động ổn định');});
test('immersive footer does not invent links or server/platform badges when optional list is empty',()=>{const html=renderToStaticMarkup(createElement(MarketingFooter,{brandSrc:'/wordmark.png',brandWidth:422,brandHeight:169,brandLabel:'Linh Giới Online',tagline:'Tagline',status:'Chưa mở',statusHref:'/download',links:[]}));expect((html.match(/<a /g)||[])).toHaveLength(1);expect(html).not.toContain('Android');expect(html).not.toContain('iOS');});
